storage: /verdaccio/storage

middlewares:
  github-oauth-ui:
    enabled: true

auth:
  github-oauth-ui:
    org: GITHUB_OAUTH_ORG
    client-id: GITHUB_OAUTH_CLIENT_ID
    client-secret: GITHUB_OAUTH_CLIENT_SECRET
    token: GITHUB_OAUTH_TOKEN

store:
  aws-s3-storage:
    bucket: S3_BUCKET
    region: S3_REGION
    accessKeyId: S3_ACCESS_KEY_ID
    secretAccessKey: S3_SECRET_ACCESS_KEY

security:
  api:
    legacy: false
    jwt:
      sign:
        expiresIn: 29d

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@origen-studio/starter*':
    access: github/org/OrigenStudio/team/starter
    publish: github/org/OrigenStudio/team/starter
    proxy: npmjs
  '@*/*':
    access: github/org/OrigenStudio
    publish: github/org/OrigenStudio
    proxy: npmjs
  '**':
    access: github/org/OrigenStudio
    publish: github/org/OrigenStudio
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
