storage: ./storage
auth:
  github-oauth-ui:
    org: GITHUB_OAUTH_ORG
    client-id: GITHUB_OAUTH_CLIENT_ID
    token: GITHUB_OAUTH_CLIENT_SECRET
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs
    access: $authenticated
    publish: $authenticated
logs:
  - {type: stdout, format: pretty, level: http}
